name: Сборка JailPlugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Скачивание репозитория
      uses: actions/checkout@v4

    - name: Установка Java 26
      uses: actions/setup-java@v4
      with:
        java-version: '26' # Указываем Java 26
        distribution: 'temurin'
        cache: maven

    - name: Сборка проекта
      run: mvn -B clean package --file pom.xml

    - name: Создание GitHub Релиза
      uses: softprops/action-gh-release@v2
      with:
        name: Релиз ${{ github.ref_name }}
        body: |
          **JailPlugin обновлен до версии 26.2 (Java 26)**
          Скачайте .jar файл ниже.
        files: target/JailPlugin-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
